Repository Taraxa-project/taraxa-platform, pull requests merged in 2022-04, with the labels that each got.

#128 #126 Fix bad undelegated number in Staking page
  services/community-site/src/pages/Staking/Staking.tsx
Labels: Mergeable

#124 #48: Change margin in delegation table
  services/community-site/src/pages/Delegation/delegation.scss
Labels: Change request

#129 #126 profile breaking fix
  services/community-site/src/pages/Profile/ViewProfile.tsx
Labels: Change request

#123 #91: Added styled components to community-site
  services/community-site/package.json
  yarn.lock
Labels: Mergeable

#132 Feature/60 claim to postgres
  services/claim-backend/.eslintrc.js
  services/claim-backend/Dockerfile
  services/claim-backend/charts/prod.values.yaml
  services/claim-backend/charts/qa.values.yaml
  services/claim-backend/config/database.ts
  services/claim-backend/docker-compose.yml
  services/claim-backend/package.json
  services/claim-backend/src/general.module.ts
  services/claim-backend/src/modules/auth/auth.service.ts
  yarn.lock
Labels: Needs review
